### Recuperar todas las tareas creadas
GET http://localhost:1234/task

### Crear una de las tareas
POST http://localhost:1234/task
Content-Type: application/json

{
  "task": "Esta es una prueba de crear una tarea"
}